services:
  jaeger:
    networks:
      - backend
    image: jaegertracing/all-in-one:latest
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    ports:
      - "4317"
      - "16686:16686"
    volumes:
      - ./jaeger-ui.json:/etc/jaeger/jaeger-ui.json

  otel_collector:
    networks:
      - backend
    image: otel/opentelemetry-collector:latest
    command: --config /etc/otelcol/otel-collector-config.yml
    ports:
      - "4317:4317"
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml
    depends_on:
      - jaeger

  victoria_metrics:
    networks:
      - backend
    image: victoriametrics/victoria-metrics:stable
    ports:
      - "8428:8428"
    volumes:
      - ./victoria-metrics-data:/victoria-metrics-data


### OPTIONAL
#   grafana:
#     networks:
#       - backend
#     image: grafana/grafana:latest
#     volumes:
#       - ./grafana.ini:/etc/grafana/grafana.ini
#       - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
#     environment:
#       - GF_AUTH_ANONYMOUS_ENABLED=true
#       - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#       - GF_AUTH_DISABLE_LOGIN_FORM=true
#     ports:
#       - 3000:3000

networks:
  backend:
