receivers:
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: http://victoria_metrics:8428/opentelemetry

  otlp/jaeger: # Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - "otlp/jaeger"
    metrics:
      receivers:
        - hostmetrics
        - otlp
      processors:
        - batch
      exporters:
        - otlphttp
